gulp/sidecarMetadata.js, gulpfile.babel.js, partials/learn/sidebar.handlebars
This lets us include .pdf (or any other type) files in sidebars simply through glob.
=> Pdf in sidebar

gulp/enhance.js, partials/head.handlebars, src/index.handlebars
This changes how titles are displayed on the developer site.
Homepage: Start Developing | Stellar Developers
Docs repo page: Operations | Stellar Developers
non-docs repo page: Building Transactions - JS Stellar Base | Stellar Developers
=> Meta improvements

gulpfile.babel.js, src/js/headingAnchorShortcut.js, src/styles/_anchorShortcut.scss, src/styles/index.scss
Looks something like this when hovered:
Implements https://github.com/stellar/developers/issues/38
=> add anchor shortcuts to headings in s-read-md

partials/learn/sidebar.handlebars
This is so that people do not get confused and start reading interstellar docs when the sdk or Horizon docs are more what they need.
- First commit simply 'unlists' it
- ~~Second commit (`remove interstellar from build process`) will cause all the current interstellar pages to become 404 pages.~~
=> Remove interstellar navigation

gulp/handlebars.js, gulpfile.babel.js, layouts/beyond-code.handlebars, layouts/learn.handlebars, layouts/reference.handlebars, layouts/tools.handlebars, partials/beyond-code/sidebar.handlebars, partials/contentWrapperStart.handlebars, partials/header-centered.handlebars, partials/header-full-with-sidebar.handlebars, partials/learn/sidebar.handlebars, partials/mainNavMenu/item.handlebars, partials/reference/sidebar.handlebars, partials/tools/sidebar.handlebars, src/index.handlebars, src/js/collapsibleListSet.js, src/styles/_collapsibleListSet.scss, src/styles/_header2016.scss, src/styles/_headerWithSidebar.scss, src/styles/_mainNavMenu.scss, src/styles/index.scss
It looks something like this:
Making the current item highlighting with the blue thing extending all the way to the left (but not limited to) made the styling extremely difficult since there are multiple levels of indentations. This is the best possible outcome with css.
The cause of this is that the design calls for a blue rectangle exactly at the left side of the nav. This is difficult to do because some items start off at different indentation levels. If we get rid of the blue rectangle or move it to the right side, then this single line highlighting issue will be gone. 
Because of how the "current" state is implemented (due to the blue rectangle), menus with a current item can not be collapsed or else the "current" state will persist with the menu closed.
This can either be solved by …
=> Header and sidebar amendments

partials/tools/sidebar.handlebars
I missed a spot when removing the xdr viewer a while ago
=> remove xdr viewer from tools sidebar

README.md, gulp/handlebars.js, gulpfile.babel.js, package.json, partials/head.handlebars
Pretty much what it says on the tin.
You can build incrementally (build only the files that changed) with:
```sh
gulp build --incremental
```
And you can watch and incrementally rebuild with:
```sh
gulp watch
```
And best of all you can serve and auto rebuild with:
```sh
gulp watch serve
```
It will also auto-reload the content in the browser for you (this was already set up, but wasn't triggered before unless you messed around in the build output files).
=> Add incremental + live building. Fixes #20.

partials/foot.handlebars, partials/head.handlebars
Missed a fingerprint call in #69, so this fixes it :\
Also fixes capitalization of HTML5 DOCYPE declaration while we’re at it.
=> Fix app.js fingerprinting (missed this in #69)

src/beyond-code
The underlying section this symlink pointed to was removed in https://github.com/stellar/docs/pull/147 and now needs to removed here.
=> Remove beyond-code section

src/js/codeExamples.js
This fixes the capitalization of “Json” (now “JSON”) for the language switcher and also fixes an issue where multiple code examples on a single page with differing sets of language options conflicted with each other (e.g. one sample also has a “JSON” option because it is describing data from Horizon while the rest are only JS/Java/Go because they are about performing an operation).
=> Minor code example fixes

gulp/math-formula.js, gulpfile.babel.js, src/styles/_mathFormula.scss, src/styles/index.scss
This adds some very simple support for nicely displaying mathematical formulas (currently used in the fees doc: https://github.com/stellar/docs/pull/155). It surrounds various tokens (parens, operators, variables, etc) with DOM elements, and cleans up typography (proper multiplication, division, ≤, ≥).
We could do something a bit richer using MathJax, but it would be much heavier weight, imposes some *slightly* less readable syntax (AsciiMath), and doesn't handle vars with spaces (as in the example above), so this simple implementation seemed to serve our purposes here a bit better. Totally open to changing that, though.
Formulas can be inline (delimited by `$$`) or block (code fences with the language set to `math-formula`, e.g:
```math-formula
(2 + [# of entries]) * [base reserve]
```
=> Add lightweight math display

gulp/links.js, gulpfile.babel.js
This allows links across repos (e.g. from a Horizon reference doc to a Stellar-Core reference doc) relative in the build.
e.g. `https://www.stellar.org/developers/stellar-core/learn/admin.html` -> `/stellar-core/learn/admin.html`
=> Make links to the dev portal (e.g. for docs in separate repos) relative in build

partials/reference/sidebar.handlebars, repos.json, src/go
This PR integrates documentation defined in our monorepo into the developers portal.
=> Expand Go SDK docs in developer portal

README.md, gulpfile.babel.js
This makes figuring out what’s going on with the CSS much easier. It could be extended in the future for uglifying/not uglifying JS, JS sourcemaps (if building with rollup, webpack, babel, etc), and so on.
=> Add debug flag to include sourcemaps in build

src/index.handlebars
There was previously no permanent page for the build challenge, so we linked to the blog post. Now that there’s a page, we should link to it instead.
=> Point build challenge link on home page to actual page (not blog)

bower.json, gulpfile.babel.js, src/js/footnotes.js, src/styles/_footnotes.scss
Basically: 
Also fixes another minor footnote styling issue (alignment of the separator line)
Uses the [Tether](http://tether.io/docs/welcome/) and [Drop](http://github.hubspot.com/drop/docs/welcome/) libraries from Hubspot, which are generally very flexible and reliable.
=> Display footnotes as popovers

gulp/enhance.js, gulp/links.js
This does a couple things:
1. Adds metadata about file sequences (e.g. multi-page guides) during build (so we can do things like make a table of contents in templates.
2. Decorates back/next links in documents with additional styling related classes. This helps keep aspects of those navigation items that are specific to the site in the developers repo while allowing the documents themselves to have the links (so they can be navigated on github) and maintain minimal markup. Used by https://github.com/stellar/docs/pull/160
=> Sequential navigation support

.gitignore, gulp/code-symbol-tags.js, gulpfile.babel.js, src/js/codeSymbolLinks.js, src/js/footnotes.js, src/styles/_codeExamples.scss, src/styles/_footnotes.scss, src/styles/_popovers.scss, src/styles/index.scss
This adds reference information about symbols in the code samples as popovers (with additional links to the actual reference docs:
At the moment, it only works for JS. The process is twofold:
1. At build time, we generate a JSON file with summarized documentation (names of symbols, a shortened description, and URLs for documentation of those symbols). This lives in the developers repo right now, but _maybe_ would be better in each SDK repo. Not sure.
2. At runtime, we load the JSON in via XHR and do a pretty naive search for matching symbol names. Since we control the samples, we can make sure we don't wind up with false matches, but a more advanced system that knows how to analyze different types of source code could do a better job at build time. I think this current system good enough …
=> WIP: Turn symbols in code samples into links/popovers

gulp/enhance.js, partials/reference/sidebar.handlebars, src/horizon, src/index.handlebars
fixed all horizon references, changing to services/horizon/internal where needed.
fixed symlink as well.
=> reroute to services/horizon/internal where needed, closes #89

src/index.handlebars
Update Go SDK link to non-deprecated repository
=> Fix Go SDK Link on developers landing page

gulp/enhance.js
Hello!
Currently "Edit this doc in GitHub" link is broken for Horizon docs (basically, all `horizon/reference/*` pages, e.g., https://www.stellar.org/developers/horizon/reference/endpoints/assets-all.html)
This PR fixes it
=> Fix link to github for horizon reference

partials/reference/sidebar.handlebars
Adds a heading to distinguish official SDKs from community SDKs. 
I waffled on what to do with the Java SDK. Considered whether to add an "official SDKs" section, add a section similar to Go and JS's SDKs, or just leave it top level. Left it top level for a minimal change, but it might warrant a bit more love.
=> Separate official SDKs from community maintained

partials/reference/sidebar.handlebars
Changes the sidebar link to point at the GoDocs for `horizonclient` and `txnbuild`, rather than the top of the monorepo.
=> link to SDK docs from sidebar

partials/reference/sidebar.handlebars, src/index.handlebars
Did a bit of reordering, fixed the Ruby link, and cleaned up the home page to look closer to the sidebar. Tested on a local build and it looks good to go by me (links all work as well).
=> Bring SDKs on home page up to date with sidebar.

partials/guides/sidebar.handlebars, src/index.handlebars
Until the guides have been thoroughly revamped, remove them from the
website.
=> Remove anchor guides sidebar and homepage link.

gulp/code-symbol-tags.js
Fixes https://github.com/stellar/developers/issues/117 - the reason for the broken build was that the command `/node_modules/.bin/jsdoc -c .jsdoc.json --explain` relied on `libdocs` existing. But it only gets created after running `yarn build:docs`.
It used to work because the `jsdoc.config` file was using the `src` directory, but with the move to TypeScript, we need to use `libdocs` which contains the transpiled source code - [see this change](https://github.com/stellar/js-stellar-sdk/commit/bf3b62ec3ba2bbeca9c6659bff572e518b9c62b9#diff-4c4e0bb5af5bd36c5762fb0883ef0752R3).
Depends on https://github.com/stellar/js-stellar-sdk/pull/380
=> Build docs with gulp before generating code symbols.

jenkins.bash
Yarn is included in the image so we can't install explicitly any more
=> Fix jenkins build

partials/head.handlebars
stellar/docs#504 highlighted that _sometimes_ the "next page" link on docs are 404'ing. I dug a little and realized it's only when the URL is missing a trailing slash, because it expects a relative path. A few lines of JS will force it to always have a trailing slash.
The analytics aren't being used for any specific reason, so I'm removing them.
=> Fix relative links, remove some analytics

src/js/codeSymbolLinks.js
I just discovered this feature and that it was broken. Using the symbols, there is some code in this library that extends the JS code snippets to display an inline box showing the documentation with the methods being used.  Let's use a fixed link since it's pretty hard to reason about the final directory hierarchy for this site ;(
=> Add fixed link to JS symbols.

.dockerignore, Dockerfile
While migrating off the old subdomain, I hit a snag because we present this content from `/developers/*` but it's technically built and served as expecting `/*`. Luckily there's an existing prefix logic we can tap into.
=> Serve from docker with `/developers` prefixed

partials/contentWrapperStart.handlebars, src/styles/index.scss
=> Make replacement content banner more visible
