stellar/developers

- gulp/enhance.js
- partials/contentWrapperStart.handlebars
- partials/head.handlebars
- partials/learn/sidebar.handlebars
- partials/modules/dev-newsletter.handlebars
- repos.json
- src/index.handlebars
- src/styles/_mailSignup.scss
- src/styles/index.scss
The commit `add project title to content title` does this:
The last 3 commits are trivial.
> Touchups 6

- partials/learn/sidebar.handlebars
This prioritizes more important stuff by pushing them higher.
> move interstellar to bottom of learn menu

- partials/learn/sidebar.handlebars
> Move Horizon > Overview to the top

- partials/learn/sidebar.handlebars
> add js-stellar-sdk api reference to learn sidebar

- src/styles/_siteFooter.scss
This contains only styling changes.
Closes https://github.com/stellar/developers/issues/35
> fix footer gap styling

- src/js/friendbot4.js
The api result is long and after scrolling to the next button, the user gets lost. This fixes that
> add check to ensure that friendbot is in view after navigating

- src/index.handlebars
Adds ability to do this: https://www.stellar.org/developers/#friendbot
> add id to friendbot area so it can be linked to

- README.md
- gulp/handlebars.js
- partials/head.handlebars
- partials/learn/sidebar.handlebars
- src/js/endpointRef.js
- src/styles/_icons.scss
- src/styles/index.scss
Implements: https://github.com/stellar/developers/issues/30
It doesn't matter whether https://github.com/stellar/horizon/pull/247 or this one is merged first. The code is designed to handle empty laboratoryUrl.
> Try it out button in reference docs examples

- README.md
Some changes to reflect what I found as I attempted to get the project up and running locally.
> A few improvements to the install/build instructions in the README

- partials/learn/sidebar.handlebars
There are users who can't find it.
> Add link to Horizon API reference in /learn

- src/styles/_codeExamples.scss
- src/styles/index.scss
Not sure how these got lost along the way, but anyhow, we need to merge them in.
> Styling fixes that should have been in #65

- .editorconfig
- .eslintignore
- .eslintrc
- gulp/enhance.js
- gulp/extract.js
- gulp/handlebars.js
- gulp/links.js
- gulp/sidecarMetadata.js
- gulpfile.babel.js
- package.json
- src/.eslintrc
- src/js/codeExamples.js
- src/js/collapsibleListSet.js
- src/js/endpointRef.js
- src/js/friendbot4.js
- src/js/linkCheck.js
Enforce some basic hygiene in the build and client scripts by adding linting support (and fixing some of the obvious and straightforward issues).
> Add ESLint, Editorconfig

- partials/modules/dev-newsletter.handlebars
- partials/modules/friendbot4.handlebars
- partials/reference/sidebar.handlebars
This PR is just a safeguard against potential exploits using `window.opener` as described in https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
> Adds rel="noopener" to blank targeted hyperlinks

- gulp/handlebars.js
I was experiencing frequent instances of inconsistent ordering of pages in sidebars, so this adds explicit sorting to those file lists.
It has the side benefit of making builds roughly 2x faster :D
> Sort results of file globs

- partials/guides/sidebar.handlebars
This isn’t really a work-in-progress, but marking it so that we don’t ship it right away. It needs to land at the same time as https://github.com/stellar/docs/pull/160.
> WIP: Sidebar updates for new anchor guide

- gulp/enhance.js
- partials/reference/sidebar.handlebars
this should fix it. ran locally and it worked.
> fix sidebar menu items

- src/index.handlebars
Reference is in `docs` subfolder.
> Fix reference link in index.handlebars

- partials/guides/sidebar.handlebars
- src/index.handlebars
Introducing walkthroughs! 
Share official Stellar tutorials, design patterns, sample implementations, etc. here.
> Adding Walkthroughs to Guides Section

- src/index.handlebars
Fixes https://github.com/stellar/docs/issues/356
> Add Scala SDK

- README.md
* Updated node to 8.X. @bartekn all tests seemed to show this working, and I couldn't get Node 4 to run here (though we should be using an actively maintained version of Node, ;))
* Removed references to bower and replaced them with yarn.
> Updated README regarding build process.

- src/index.handlebars
Add the TOML guide to the main list of developer guides on the
developers homepage.
> Add Stellar TOML Guide to list of dev guides.

- partials/reference/sidebar.handlebars
Compare to list at the bottom of https://www.stellar.org/developers/reference/
> Update sidebar to current list of SDKs

- gulpfile.babel.js
- src/js/syntaxHighlight.js
https://github.com/stellar/docs/pull/531
https://github.com/stellar/docs/pull/532
> Add syntax highlighting for Python.

- partials/contentWrapperStart.handlebars
This is extremely rough copy, should be iterated on. Tested locally and this works though
> Add replacement message
